### ISSUE TITLE
webpack production build

### ISSUE THREAD

**Issue by mat10tng** [factn/mutualaidworld_frontend#14]
We are having some trouble with minimization and webpack. Try npm run build from master branch

I traced the error to this:
https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/234

If anyone want to do something about it, be my guest, I will remove the webpack config in heroku branch for now untill someone can provide a better config

**Comment by utunga** [comment]
Grr.. FWIW I have found that 90% of the time these annoying webpack build errors are due to versions of the libraries not being consistent with when first developed and/or the version of node having been upgraded. The easy way around it is usually just to re-scaffold with a more recent version of node and then specify the exact engine in the package.json ( using the "engines" field etc)
