### ISSUE TITLE
Potential security issue

### ISSUE THREAD

**Issue by lucasgrelaud** [factn/mutualaidworld_frontend#57]
Hi,
I noticed you've left sensitive information in the following file;
 - [Firebase credentials](https://github.com/factn/mutualaidworld_frontend/blob/master/src/config/firebase.ts)

This may lead to a security issue in your app, so you should remove these informations from your repository.

Regards,
Lucas GRELAUD

**Comment by mat10tng** [comment]
Hi! Agree, we will do that after our mvp is done. Once we decided to go to production, all databases will be purge and we will be keeping secret locally

**Comment by lucasgrelaud** [comment]
Alright !

**Comment by considine** [comment]
Hey guys,
It might be a good idea to add firebase config to .gitignore, but I believe that's more of a personal preference thing than a security issue. Firebase apps use their credentials on the client side meaning any firebase app is exposing these credentials to the web. Security holes are prevented by adding database rules to vet queries / mutations rather than by hiding credentials which inevitably appear in network requests etc
